---
# tasks/main.yml

- name: Ensure PostgreSQL data directory exists
  become: true
  file:
    path: "{{ postgres_data_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Run PostgreSQL container
  become: true
  community.docker.docker_container:
    name: "{{ postgres_container_name }}"
    image: "{{ postgres_image }}"
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_network_name }}"
    ports:
      - "{{ postgres_external_port }}:{{ postgres_container_port }}"
    volumes:
      - "{{ postgres_data_path }}:/var/lib/postgresql/data"
    env:
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_DB: "{{ postgres_db }}"
