---
# handlers/main.yml

- name: reload systemd
  become: true
  command: systemctl daemon-reload
  listen: reload systemd

- name: restart docker
  become: true
  service:
    name: docker
    state: restarted
