---
# tasks/main.yml

- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install essential packages
  apt:
    name:
      - python3-pip
      - python3-venv
      - git
      - curl
      - vim
    state: present
  when: ansible_os_family == 'Debian'

- name: Create project directory
  file:
    path: /opt/oneclickteach
    state: directory
    mode: '0755'
    owner: root
    group: root
