---
- name: Setup server
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: common
    - role: docker
    - role: services
      vars:
        oneclickteach_api_image: "{{ oneclickteach_api.image }}"
        oneclickteach_api_container_name: "{{ oneclickteach_api.container_name }}"
        oneclickteach_api_container_port: "{{ oneclickteach_api.container_port }}"
        oneclickteach_api_external_port: "{{ oneclickteach_api.external_port }}"
