---
- name: Setup server
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: common
      vars:
        proxy_is_enabled: "{{ proxy.is_enabled }}"
        http_proxy: "{{ proxy.http_proxy }}"
        https_proxy: "{{ proxy.https_proxy }}"
    - role: docker
      vars:
        proxy_is_enabled: "{{ proxy.is_enabled }}"
        http_proxy: "{{ proxy.http_proxy }}"
        https_proxy: "{{ proxy.https_proxy }}"
    - role: services
      vars:
        oneclickteach_api_image: "{{ oneclickteach_api.image }}"
        oneclickteach_api_container_name: "{{ oneclickteach_api.container_name }}"
        oneclickteach_api_container_port: "{{ oneclickteach_api.container_port }}"
        oneclickteach_api_external_port: "{{ oneclickteach_api.external_port }}"
